In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('customer.csv')

In [3]:
df.head()

,age,gender,review,education,purchased
0,30,Female,Average,School,No
1,68,Female,Poor,UG,No
2,70,Female,Good,PG,No
3,72,Female,Good,PG,No
4,16,Female,Average,UG,No


In [4]:
df = df.iloc[:, 2:]

In [5]:
df.head()

,review,education,purchased
0,Average,School,No
1,Poor,UG,No
2,Good,PG,No
3,Good,PG,No
4,Average,UG,No


In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 0:2], df.iloc[:, -1], test_size=0.2, random_state=42)

In [53]:
print(type(X_train))
print(type(y_train))

<class 'numpy.ndarray'>
<class 'pandas.core.series.Series'>


In [7]:
X_train

,review,education
12,Poor,School
4,Average,UG
37,Average,PG
8,Average,UG
3,Good,PG
6,Good,School
41,Good,PG
46,Poor,PG
47,Good,PG
15,Poor,UG


In [8]:
from sklearn.preprocessing import OrdinalEncoder

In [9]:
oe = OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [ ]:
oe.categories_

# the reason for the error

# The reason is very subtle but important.
# You defined categories in the constructor, but the encoder is still not fitted.
# In scikit-learn, attributes ending with _ (like categories_, coef_, mean_) are created only 
# after fit() is called.

AttributeError: 'OrdinalEncoder' object has no attribute 'categories_'

In [11]:
oe.feature_names_in_

AttributeError: 'OrdinalEncoder' object has no attribute 'feature_names_in_'

### Attribute	Meaning
1. categories	-> What you provided manually
2. categories_	-> What the model learned during fit()

One more subtle ML detail

When you manually define categories, OrdinalEncoder will NOT learn new ones.

Example:

If test data contains "Excellent" → it will throw an error.

To handle this we often use:

OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)

In [13]:
# this is working 
oe.categories

[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']]

In [14]:
oe.fit(X_train)

,categories,"[['Poor', 'Average', ...], ['School', 'UG', ...]]"
,dtype,<class 'numpy.float64'>
,handle_unknown,'error'
,unknown_value,None
,encoded_missing_value,nan
,min_frequency,None
,max_categories,None


In [15]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [16]:
X_train

array([[0., 0.],
       [1., 1.],
       [1., 2.],
       [1., 1.],
       [2., 2.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [2., 2.],
       [0., 1.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [1., 1.],
       [2., 1.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [1., 0.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.]])

In [17]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [18]:
oe.feature_names_in_

array(['review', 'education'], dtype=object)

In [19]:
oe.inverse_transform(np.array([0, 2]).reshape(1, 2))

array([['Poor', 'PG']], dtype=object)

In [20]:
oe.get_feature_names_out()

array(['review', 'education'], dtype=object)

In [21]:
oe.transform(np.array(['Poor', 'College']).reshape(1, 2))

c:\Users\v-guptaarpit\OneDrive - Microsoft\Documents\projects\Deep_Learning_NLP\venv\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


ValueError: Found unknown categories [np.str_('College')] in column 1 during transform

#### how to handle unknown values

In [22]:
oe = OrdinalEncoder(
    categories=[['Poor', 'Average', 'Excellent'], ['School', 'UG', 'PG']],
    handle_unknown='use_encoded_value',
    unknown_value=-1,
)

X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, :2], df.iloc[:, -1], test_size=0.2, 
                                                    random_state=42)
X_train = oe.fit_transform(X_train)
oe.transform(np.array(['Poor', 'College']).reshape(1, 2))

c:\Users\v-guptaarpit\OneDrive - Microsoft\Documents\projects\Deep_Learning_NLP\venv\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[ 0., -1.]])

#### Handling infrequent (Rare) Categories

In [41]:
X = np.array([['dog'] * 5 + ['cat'] * 20 + ['rabbit'] * 10 + ['snake'] * 3 + ['horse'] * 2], dtype=object).T
X

array([['dog'],
       ['dog'],
       ['dog'],
       ['dog'],
       ['dog'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['snake'],
       ['snake'],
       ['snake'],
       ['horse'],
       ['horse']], dtype=object)

In [42]:
'''it sorts the categories by their frequencies and then picks the (max_categories-1) from the top
 and then combines the remaining which is going to the last category.
'''

enc = OrdinalEncoder(max_categories=3).fit(X)

In [43]:
enc.infrequent_categories_

[array(['dog', 'horse', 'snake'], dtype=object)]

In [44]:
enc.transform(np.array([['cat', 'rabbit', 'snake', 'dog', 'horse']]).reshape(5, 1))

array([[0.],
       [1.],
       [2.],
       [2.],
       [2.]])

In [47]:
''' 
only consider the categories which have frequency >= min_frequency
rest of them -> consider in others
'''

enc = OrdinalEncoder(min_frequency=4).fit(X)
enc.infrequent_categories_

[array(['horse', 'snake'], dtype=object)]

In [48]:
enc.transform(np.array([['cat', 'rabbit', 'snake', 'dog', 'horse']]).reshape(5, 1))

array([[0.],
       [2.],
       [3.],
       [1.],
       [3.]])

#### Deal with Missing Values

In [ ]:
# categorical data with missing values
data = [['Cat'], [np.nan], ['Dog'], ['Fish'], [np.nan]]

# setting encoded_missing_values to -1, indicating we want missing values to be encoded as -1
encoder = OrdinalEncoder(encoded_missing_value=-1)
encoded_data = encoder.fit_transform(data)
print(encoded_data)

[[ 0.]
 [nan]
 [ 1.]
 [ 2.]
 [nan]]


In [51]:
# or set it to np.nan
encoder = OrdinalEncoder(encoded_missing_value=np.nan)
encoded_data = encoder.fit_transform(data)
print(encoded_data)

[[ 0.]
 [nan]
 [ 1.]
 [ 2.]
 [nan]]


### Label Encoding

In [54]:
## only for the label values

from sklearn.preprocessing import LabelEncoder

In [55]:
le = LabelEncoder()

In [56]:
le.fit(y_train)

LabelEncoder()

In [57]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [58]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [59]:
y_train

array([0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0])

In [60]:
le.inverse_transform([1, 1, 0])

array(['Yes', 'Yes', 'No'], dtype=object)

### One Hot Encoder