### chatgpt link: https://chatgpt.com/share/69bb021a-3678-8008-9e72-7ed26b27dbc7

In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am good developer',
    'understand the meaning of words',
    'your videos are good',
]

In [5]:
## Define the vocab size

voc_size = 10000

In [7]:
i = 1
for word in sent:
    print(word)
    print(i)
    i += 1

the glass of milk
1
the glass of juice
2
the cup of tea
3
I am a good boy
4
I am good developer
5
understand the meaning of words
6
your videos are good
7


In [8]:
## One Hot Representation 

one_hot_repr = [one_hot(words, voc_size) for words in sent]
one_hot_repr

[[5326, 9469, 2943, 9126],
 [5326, 9469, 2943, 9211],
 [5326, 1398, 2943, 3610],
 [3519, 9837, 1520, 2091, 9574],
 [3519, 9837, 2091, 6980],
 [7056, 5326, 3985, 2943, 1824],
 [9990, 9806, 327, 2091]]

In [11]:
print(type(one_hot_repr))

<class 'list'>


In [12]:
# word embedding representation

from tensorflow.keras.layers import Embedding
# from tensorflow.keras.processing.sequence import pad_sequences  # deprecated
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [13]:
import numpy as np

In [16]:
# to make the length of the all the sentences equal

sent_length = 8         # take the max_length across all sentences, or more than that

# either we can add zeros in the beginning of the sentence to make them equal to 8 or at the last(padding = 'post')
embedded_docs = pad_sequences(one_hot_repr, padding = 'pre', maxlen = sent_length)
print(embedded_docs)

[[   0    0    0    0 5326 9469 2943 9126]
 [   0    0    0    0 5326 9469 2943 9211]
 [   0    0    0    0 5326 1398 2943 3610]
 [   0    0    0 3519 9837 1520 2091 9574]
 [   0    0    0    0 3519 9837 2091 6980]
 [   0    0    0 7056 5326 3985 2943 1824]
 [   0    0    0    0 9990 9806  327 2091]]


In [17]:
## feature representation

dim = 10

In [18]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_shape=(sent_length,)))     # just like we add hidden layers by using model.add(Dense())
model.compile('adam', 'mse')        # adam optimiser, mse loss function

/Users/arpitgupta/Documents/Deep_Learning_NLP/venv310/lib/python3.10/site-packages/keras/src/layers/core/embedding.py:100: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [19]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# every word is represented by 10 dimensions here

model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step


array([[[ 3.20691131e-02,  3.91167738e-02,  7.57799298e-03,
          3.22103016e-02,  9.00208950e-03,  1.93472020e-02,
          1.70319937e-02,  4.39672545e-03, -2.40442753e-02,
          1.29698180e-02],
        [ 3.20691131e-02,  3.91167738e-02,  7.57799298e-03,
          3.22103016e-02,  9.00208950e-03,  1.93472020e-02,
          1.70319937e-02,  4.39672545e-03, -2.40442753e-02,
          1.29698180e-02],
        [ 3.20691131e-02,  3.91167738e-02,  7.57799298e-03,
          3.22103016e-02,  9.00208950e-03,  1.93472020e-02,
          1.70319937e-02,  4.39672545e-03, -2.40442753e-02,
          1.29698180e-02],
        [ 3.20691131e-02,  3.91167738e-02,  7.57799298e-03,
          3.22103016e-02,  9.00208950e-03,  1.93472020e-02,
          1.70319937e-02,  4.39672545e-03, -2.40442753e-02,
          1.29698180e-02],
        [ 8.67869705e-03, -7.94965029e-03,  1.46521218e-02,
         -3.57791558e-02,  1.18370652e-02,  1.71936676e-03,
          8.90804455e-03,  3.45054753e-02,  3.470316

In [21]:
embedded_docs[0]

array([   0,    0,    0,    0, 5326, 9469, 2943, 9126], dtype=int32)

In [26]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None
  • kwargs=<class 'inspect._empty'>

In [27]:
'''

🔴 Problem
model.predict(embedded_docs[0])

This throws:

ValueError: Cannot take the length of shape with unknown rank
🔍 Root Cause (VERY IMPORTANT)

Your model expects input shape:

(input_shape=(8,))

So Keras expects:

(batch_size, 8)
✅ What you're passing
embedded_docs[0]

Shape:

(8,)

👉 This is 1D (no batch dimension)

❌ What model expects
(1, 8)

👉 2D input (batch included)

🧠 Key Concept
Keras ALWAYS expects batch dimension

Even for a single sample:

Case	Shape
Single sentence	(1, 8)
Multiple sentences	(n, 8)
✅ Fix (Simple)
✔ Option 1: Use reshape
model.predict(embedded_docs[0].reshape(1, -1))
✔ Option 2: Use slicing (cleaner)
model.predict(embedded_docs[0:1])

👉 This keeps it 2D automatically

✔ Option 3: Use np.expand_dims
np.expand_dims(embedded_docs[0], axis=0)
🔬 Why This Error Happens (Advanced Insight)

When you pass:

(8,)

Keras cannot determine:

Is this 1 sample with 8 features?

Or 8 samples with 1 feature?

👉 Ambiguity → leads to "unknown rank" error

🔥 What Your Model Is Actually Doing

Let’s connect everything:

Input
(1, 8)
After Embedding
(1, 8, 10)

Meaning:

1 sentence

8 words

each word → 10-dimensional vector

🧠 Bonus Insight (VERY IMPORTANT FOR INTERVIEWS)
Why embedding works here:

Your pipeline:

Text → one_hot → integers → embedding → dense vectors

Example:

"glass" → 345 → [0.2, -0.1, ..., 0.7]

👉 Embedding layer = trainable lookup table

⚡ Extra Tip (Subtle but Important)

This line:

model.compile('adam', 'mse')

👉 You're not actually training anything (no fit())

So:

embeddings are random

predict() just returns random vectors

✅ Final Fix Summary

Replace:

model.predict(embedded_docs[0])

With:

model.predict(embedded_docs[0:1])
'''

'\n\n🔴 Problem\nmodel.predict(embedded_docs[0])\n\nThis throws:\n\nValueError: Cannot take the length of shape with unknown rank\n🔍 Root Cause (VERY IMPORTANT)\n\nYour model expects input shape:\n\n(input_shape=(8,))\n\nSo Keras expects:\n\n(batch_size, 8)\n✅ What you\'re passing\nembedded_docs[0]\n\nShape:\n\n(8,)\n\n👉 This is 1D (no batch dimension)\n\n❌ What model expects\n(1, 8)\n\n👉 2D input (batch included)\n\n🧠 Key Concept\nKeras ALWAYS expects batch dimension\n\nEven for a single sample:\n\nCase\tShape\nSingle sentence\t(1, 8)\nMultiple sentences\t(n, 8)\n✅ Fix (Simple)\n✔ Option 1: Use reshape\nmodel.predict(embedded_docs[0].reshape(1, -1))\n✔ Option 2: Use slicing (cleaner)\nmodel.predict(embedded_docs[0:1])\n\n👉 This keeps it 2D automatically\n\n✔ Option 3: Use np.expand_dims\nnp.expand_dims(embedded_docs[0], axis=0)\n🔬 Why This Error Happens (Advanced Insight)\n\nWhen you pass:\n\n(8,)\n\nKeras cannot determine:\n\nIs this 1 sample with 8 features?\n\nOr 8 samples with 1 fe

In [ ]:
model.predict(embedded_docs[0].reshape(-1, 1))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step


array([[[ 0.03206911,  0.03911677,  0.00757799,  0.0322103 ,
          0.00900209,  0.0193472 ,  0.01703199,  0.00439673,
         -0.02404428,  0.01296982]],

       [[ 0.03206911,  0.03911677,  0.00757799,  0.0322103 ,
          0.00900209,  0.0193472 ,  0.01703199,  0.00439673,
         -0.02404428,  0.01296982]],

       [[ 0.03206911,  0.03911677,  0.00757799,  0.0322103 ,
          0.00900209,  0.0193472 ,  0.01703199,  0.00439673,
         -0.02404428,  0.01296982]],

       [[ 0.03206911,  0.03911677,  0.00757799,  0.0322103 ,
          0.00900209,  0.0193472 ,  0.01703199,  0.00439673,
         -0.02404428,  0.01296982]],

       [[ 0.0086787 , -0.00794965,  0.01465212, -0.03577916,
          0.01183707,  0.00171937,  0.00890804,  0.03450548,
          0.03470317, -0.03006419]],

       [[ 0.01267996,  0.01109824, -0.02120324,  0.03538163,
          0.04638814, -0.03180102,  0.01874885, -0.02113428,
          0.00522212,  0.02850665]],

       [[-0.01689928,  0.03465611, -0.00

In [29]:
model.predict(embedded_docs[0][0].reshape(-1, 1))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step


array([[[ 0.03206911,  0.03911677,  0.00757799,  0.0322103 ,
          0.00900209,  0.0193472 ,  0.01703199,  0.00439673,
         -0.02404428,  0.01296982]]], dtype=float32)

In [30]:
'''
Great question — this is a very important concept in deep learning 👍

Let’s break it down step by step so you fully understand where that 100,000 is coming from.

🔹 Given Layer
Embedding(input_dim=?, output_dim=10, input_length=8)
Output Shape: (None, 8, 10)
Params: 100,000
🔹 Key Idea: How Embedding Parameters Are Calculated

For an Embedding layer, the number of parameters is:

Parameters
=
input_dim
×
output_dim
Parameters=input_dim×output_dim
🔹 What Each Term Means
1. input_dim

Size of your vocabulary

Total number of unique tokens/words

👉 Let’s call it V

2. output_dim = 10

Size of each embedding vector

Each word is represented as a vector of size 10

3. input_length = 8

Length of each input sequence

IMPORTANT: This does NOT affect parameter count

🔹 Now Let’s Compute

You are told:

Total params = 100,000
output_dim = 10

So:

𝑉
×
10
=
100000
V×10=100000
𝑉
=
10000
V=10000
✅ Final Interpretation

Your layer is equivalent to:

Embedding(input_dim=10000, output_dim=10, input_length=8)
🔹 What This Means Conceptually

Think of the embedding layer as a lookup table (matrix):

Word Index	Embedding Vector (size 10)
0	[0.2, 0.1, ..., 0.9]
1	[...]
...	...
9999	[...]

So the embedding matrix is:

(
10000
×
10
)
(10000×10)

👉 Total values = 100,000 parameters

🔹 Why Sequence Length (8) Doesn’t Matter

Output shape:

(None, 8, 10)

8 → number of words in input sequence

10 → embedding size

But:
👉 The same embedding matrix is reused for every position
👉 So it does NOT increase parameters

🔥 Intuition (Very Important)

Embedding layer = learnable dictionary

Each word has its own vector

Total parameters = number of words × vector size

🔹 Quick Rule You Should Remember
Embedding Params = Vocabulary Size × Embedding Dimension
🚀 Bonus (Advanced Insight)

Why is this powerful?

Instead of:

One-hot vector → size 10000

You compress it into:

Dense vector → size 10

👉 Massive dimensionality reduction
👉 Captures semantic meaning (similar words → similar vectors)
'''

'\nGreat question — this is a very important concept in deep learning 👍\n\nLet’s break it down step by step so you fully understand where that 100,000 is coming from.\n\n🔹 Given Layer\nEmbedding(input_dim=?, output_dim=10, input_length=8)\nOutput Shape: (None, 8, 10)\nParams: 100,000\n🔹 Key Idea: How Embedding Parameters Are Calculated\n\nFor an Embedding layer, the number of parameters is:\n\nParameters\n=\ninput_dim\n×\noutput_dim\nParameters=input_dim×output_dim\n🔹 What Each Term Means\n1. input_dim\n\nSize of your vocabulary\n\nTotal number of unique tokens/words\n\n👉 Let’s call it V\n\n2. output_dim = 10\n\nSize of each embedding vector\n\nEach word is represented as a vector of size 10\n\n3. input_length = 8\n\nLength of each input sequence\n\nIMPORTANT: This does NOT affect parameter count\n\n🔹 Now Let’s Compute\n\nYou are told:\n\nTotal params = 100,000\noutput_dim = 10\n\nSo:\n\n𝑉\n×\n10\n=\n100000\nV×10=100000\n𝑉\n=\n10000\nV=10000\n✅ Final Interpretation\n\nYour layer is equ