In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am good developer',
    'understand the meaning of words',
    'your videos are good',
]

In [4]:
## Define the vocab size

voc_size = 10000

In [5]:
## One Hot Representation 

one_hot_repr = [one_hot(words, voc_size) for words in sent]
one_hot_repr

[[7875, 4566, 6544, 6939],
 [7875, 4566, 6544, 4344],
 [7875, 4133, 6544, 9919],
 [559, 9583, 9053, 5499, 6166],
 [559, 9583, 5499, 3804],
 [5760, 7875, 2787, 6544, 1827],
 [5214, 4126, 5105, 5499]]

In [7]:
# word embedding representation

from tensorflow.keras.layers import Embedding
# from tensorflow.keras.processing.sequence import pad_sequences  # deprecated
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [ ]:
# to make the length of the all the sentences equal

sent_length = 8         # take the max_length across all sentences, or more than that

# either we can add zeros in the beginning of the sentence to make them equal to 8 or at the last(padding = 'post')
embedded_docs = pad_sequences(one_hot_repr, padding = 'pre', maxlen = sent_length)
print(embedded_docs)

[[   0    0    0    0 7875 4566 6544 6939]
 [   0    0    0    0 7875 4566 6544 4344]
 [   0    0    0    0 7875 4133 6544 9919]
 [   0    0    0  559 9583 9053 5499 6166]
 [   0    0    0    0  559 9583 5499 3804]
 [   0    0    0 5760 7875 2787 6544 1827]
 [   0    0    0    0 5214 4126 5105 5499]]


In [11]:
## feature representation

dim = 10

In [16]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_shape=(sent_length,)))
model.compile('adam', 'mse')        # adam optimiser, mse loss function

/Users/arpitgupta/Documents/Deep_Learning_NLP/venv/lib/python3.13/site-packages/keras/src/layers/core/embedding.py:103: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [17]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)