#### np.sort

In [5]:
# python sort always returns a list, thats why we are using np.sort
# np.sort returns numpy array in sorted form
import numpy as np
a = np.random.randint(1, 100, 15)
print(a)
np.sort(a)

[53 77 47 83 55 28 41  4 38 94 77 52 14 11 75]


array([ 4, 11, 14, 28, 38, 41, 47, 52, 53, 55, 75, 77, 77, 83, 94],
      dtype=int32)

In [9]:
# Sort in descending Order
np.sort(a)[::-1]

array([94, 83, 77, 77, 75, 55, 53, 52, 47, 41, 38, 28, 14, 11,  4],
      dtype=int32)

In [8]:
b = np.random.randint(1, 100, 24).reshape(6, 4)
print(b)
print(np.sort(b))

[[99 70 84 75]
 [21 73 65 23]
 [61 49 85 57]
 [52 15 83 59]
 [40 13  8 44]
 [75 90 91 66]]
[[70 75 84 99]
 [21 23 65 73]
 [49 57 61 85]
 [15 52 59 83]
 [ 8 13 40 44]
 [66 75 90 91]]


In [10]:
# sort column wise
np.sort(b, axis=0)

array([[21, 13,  8, 23],
       [40, 15, 65, 44],
       [52, 49, 83, 57],
       [61, 70, 84, 59],
       [75, 73, 85, 66],
       [99, 90, 91, 75]], dtype=int32)

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

In [11]:
a

array([53, 77, 47, 83, 55, 28, 41,  4, 38, 94, 77, 52, 14, 11, 75],
      dtype=int32)

In [12]:
np.append(a, 200)

array([ 53,  77,  47,  83,  55,  28,  41,   4,  38,  94,  77,  52,  14,
        11,  75, 200])

In [13]:
b

array([[99, 70, 84, 75],
       [21, 73, 65, 23],
       [61, 49, 85, 57],
       [52, 15, 83, 59],
       [40, 13,  8, 44],
       [75, 90, 91, 66]], dtype=int32)

In [15]:
# we want to add a column
np.append(b, np.ones((b.shape[0], 1)), axis=1)

array([[99., 70., 84., 75.,  1.],
       [21., 73., 65., 23.,  1.],
       [61., 49., 85., 57.,  1.],
       [52., 15., 83., 59.,  1.],
       [40., 13.,  8., 44.,  1.],
       [75., 90., 91., 66.,  1.]])

In [16]:
np.append(b, np.random.random((b.shape[0], 1)), axis=1)

array([[99.        , 70.        , 84.        , 75.        ,  0.81643847],
       [21.        , 73.        , 65.        , 23.        ,  0.63451478],
       [61.        , 49.        , 85.        , 57.        ,  0.84228246],
       [52.        , 15.        , 83.        , 59.        ,  0.53968986],
       [40.        , 13.        ,  8.        , 44.        ,  0.77257892],
       [75.        , 90.        , 91.        , 66.        ,  0.83314307]])

### 🔑 The Golden Rule (MOST IMPORTANT)

👉 axis tells you the direction you move ALONG, not what you operate ON

axis=0 → move down the rows (vertical direction ⬇️)
axis=1 → move across columns (horizontal direction ➡️)

### np.concatenate

np.concatenate() function concatenate a sequence of arrays along an existing axis.

In [17]:
c = np.arange(6).reshape(2, 3)
d = np.arange(6, 12).reshape(2, 3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [18]:
np.concatenate((c, d), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [19]:
np.concatenate((c, d), axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique
With the help of np.unique() method, we can get the unique values from the array given as parameter in np.unique() method.

In [21]:
e = np.array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, ])
f = np.array([[1, 2, 3, 1], [1, 2, 3, 2]])
print(np.unique(e))
print(np.unique(f))


[1 2 3 4 5 6]
[1 2 3]


### np.expand_dims
With the help of numpy.expand_dims() method, we can get the expanded dimensions of an array.

In [25]:
print(a)
print(a.shape)

[53 77 47 83 55 28 41  4 38 94 77 52 14 11 75]
(15,)


In [30]:
print(np.expand_dims(a, axis=0))
np.expand_dims(a, axis=0).shape

[[53 77 47 83 55 28 41  4 38 94 77 52 14 11 75]]


(1, 15)

In [32]:
print(np.expand_dims(a, axis=1))
np.expand_dims(a, axis=1).shape

[[53]
 [77]
 [47]
 [83]
 [55]
 [28]
 [41]
 [ 4]
 [38]
 [94]
 [77]
 [52]
 [14]
 [11]
 [75]]


(15, 1)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given array condition is satisfied.

In [43]:
a

array([53, 77, 47, 83, 55, 28, 41,  4, 38, 94, 77, 52, 14, 11, 75],
      dtype=int32)

In [44]:
# find all indices with value > 50
np.where(a > 50)

(array([ 0,  1,  3,  4,  9, 10, 11, 14]),)

In [45]:
# replace all values > 50 with 0
np.where(a > 50, 0, a)

array([ 0,  0, 47,  0,  0, 28, 41,  4, 38,  0,  0,  0, 14, 11,  0],
      dtype=int32)

In [46]:
# replace all even numbers by 0
np.where(a%2==0, 0, a)

array([53, 77, 47, 83, 55,  0, 41,  0,  0,  0, 77,  0,  0, 11, 75],
      dtype=int32)

### np.argmax
The numpy.argmax() function returns indices of the max element of the array in a particular axis.

In [47]:
a

array([53, 77, 47, 83, 55, 28, 41,  4, 38, 94, 77, 52, 14, 11, 75],
      dtype=int32)

In [48]:
np.argmax(a)

np.int64(9)

In [49]:
b

array([[99, 70, 84, 75],
       [21, 73, 65, 23],
       [61, 49, 85, 57],
       [52, 15, 83, 59],
       [40, 13,  8, 44],
       [75, 90, 91, 66]], dtype=int32)

In [50]:
# column wise, travelling vertically down
np.argmax(b, axis=0)

array([0, 5, 5, 0])

In [51]:
# row wise, travelling side ways
np.argmax(b, axis=1)

array([0, 1, 2, 2, 3, 2])

### np.argmin

In [ ]:
# similar to argmax, but returns the min

### np.cumsum

np.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

In [56]:
a

array([53, 77, 47, 83, 55, 28, 41,  4, 38, 94, 77, 52, 14, 11, 75],
      dtype=int32)

In [57]:
np.cumsum(a)

array([ 53, 130, 177, 260, 315, 343, 384, 388, 426, 520, 597, 649, 663,
       674, 749])

In [53]:
b

array([[99, 70, 84, 75],
       [21, 73, 65, 23],
       [61, 49, 85, 57],
       [52, 15, 83, 59],
       [40, 13,  8, 44],
       [75, 90, 91, 66]], dtype=int32)

In [ ]:
# column wise, travelling down vertically, axis=0
np.cumsum(b, axis=0)

array([[ 99,  70,  84,  75],
       [120, 143, 149,  98],
       [181, 192, 234, 155],
       [233, 207, 317, 214],
       [273, 220, 325, 258],
       [348, 310, 416, 324]])

In [55]:
# row wise, travelling horizontally sideways, axis=1
np.cumsum(b, axis=1)

array([[ 99, 169, 253, 328],
       [ 21,  94, 159, 182],
       [ 61, 110, 195, 252],
       [ 52,  67, 150, 209],
       [ 40,  53,  61, 105],
       [ 75, 165, 256, 322]])

### np.cumprod()

In [58]:
a

array([53, 77, 47, 83, 55, 28, 41,  4, 38, 94, 77, 52, 14, 11, 75],
      dtype=int32)

In [59]:
np.cumprod(a)

array([                  53,                 4081,               191807,
                   15919981,            875598955,          24516770740,
              1005187600340,        4020750401360,      152788515251680,
          14362120433657920,  1105883273391659840,  2165697995237656832,
       -6573716214091907584,  1476097939827223040,    26881044784418304])

In [60]:
b

array([[99, 70, 84, 75],
       [21, 73, 65, 23],
       [61, 49, 85, 57],
       [52, 15, 83, 59],
       [40, 13,  8, 44],
       [75, 90, 91, 66]], dtype=int32)

In [61]:
np.cumprod(b, axis=0)

array([[         99,          70,          84,          75],
       [       2079,        5110,        5460,        1725],
       [     126819,      250390,      464100,       98325],
       [    6594588,     3755850,    38520300,     5801175],
       [  263783520,    48826050,   308162400,   255251700],
       [19783764000,  4394344500, 28042778400, 16846612200]])

In [62]:
np.cumprod(b, axis=1)

array([[      99,     6930,   582120, 43659000],
       [      21,     1533,    99645,  2291835],
       [      61,     2989,   254065, 14481705],
       [      52,      780,    64740,  3819660],
       [      40,      520,     4160,   183040],
       [      75,     6750,   614250, 40540500]])

### np.percentile

numpy.percentile() function is used to compute the nth percentile of the given data(array elements) along the specified axis.

In [63]:
a

array([53, 77, 47, 83, 55, 28, 41,  4, 38, 94, 77, 52, 14, 11, 75],
      dtype=int32)

In [ ]:
# 100 percentile will always be maximum because no one is above him.
np.percentile(a, 100)

np.float64(94.0)

In [ ]:
# 0 percentile will always be minimum, because no 
np.percentile(a, 0)

np.float64(4.0)

In [ ]:
# both these values will be same
print(np.percentile(a, 50))
print(np.median(a)) 

# half of the people are behind him
# check the formula for percentile
# Percentile = (Number of Values Below “x” / Total Number of Values) × 100

52.0
52.0


### np.histogram
numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form

In [68]:
a

array([53, 77, 47, 83, 55, 28, 41,  4, 38, 94, 77, 52, 14, 11, 75],
      dtype=int32)

In [70]:
np.histogram(a, bins=[0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

(array([1, 2, 1, 1, 2, 3, 0, 3, 1, 1]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [71]:
# bin size can by anything we want
np.histogram(a, bins=[0, 50, 100])

(array([7, 8]), array([  0,  50, 100]))

### np.corrcoef
Return Pearson product-moment correlation coefficients.

In [ ]:
salary = np.array([20000, 40000, 25000, 35000, 60000])
experience = np.array([1, 2, 3, 4, 5])

# read about this

np.corrcoef(salary, experience)

array([[1.        , 0.76150962],
       [0.76150962, 1.        ]])

### np.isin
With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [73]:
a

array([53, 77, 47, 83, 55, 28, 41,  4, 38, 94, 77, 52, 14, 11, 75],
      dtype=int32)

In [74]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([], dtype=int32)

### np.flip
The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [75]:
a

array([53, 77, 47, 83, 55, 28, 41,  4, 38, 94, 77, 52, 14, 11, 75],
      dtype=int32)

In [76]:
np.flip(a)

array([75, 11, 14, 52, 77, 94, 38,  4, 41, 28, 55, 83, 47, 77, 53],
      dtype=int32)

In [77]:
b

array([[99, 70, 84, 75],
       [21, 73, 65, 23],
       [61, 49, 85, 57],
       [52, 15, 83, 59],
       [40, 13,  8, 44],
       [75, 90, 91, 66]], dtype=int32)

In [78]:
np.flip(b, axis=0)

array([[75, 90, 91, 66],
       [40, 13,  8, 44],
       [52, 15, 83, 59],
       [61, 49, 85, 57],
       [21, 73, 65, 23],
       [99, 70, 84, 75]], dtype=int32)

In [79]:
np.flip(b, axis=1)

array([[75, 84, 70, 99],
       [23, 65, 73, 21],
       [57, 85, 49, 61],
       [59, 83, 15, 52],
       [44,  8, 13, 40],
       [66, 91, 90, 75]], dtype=int32)

### np.put
The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [80]:
a

array([53, 77, 47, 83, 55, 28, 41,  4, 38, 94, 77, 52, 14, 11, 75],
      dtype=int32)

In [82]:
np.put(a,[0,1],[110,530])
a

array([110, 530,  47,  83,  55,  28,  41,   4,  38,  94,  77,  52,  14,
        11,  75], dtype=int32)

### np.delete
The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [83]:
a

array([110, 530,  47,  83,  55,  28,  41,   4,  38,  94,  77,  52,  14,
        11,  75], dtype=int32)

In [84]:
np.delete(a, [0, 2, 4])

array([530,  83,  28,  41,   4,  38,  94,  77,  52,  14,  11,  75],
      dtype=int32)

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [85]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [86]:
np.intersect1d(m,n)

array([3, 4, 5])

In [87]:
np.setdiff1d(n,m)

array([6, 7])

In [88]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [89]:
m[np.in1d(m,1)]

C:\Users\v-guptaarpit\AppData\Local\Temp\ipykernel_39352\524887286.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m,1)]


array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [90]:
a

array([110, 530,  47,  83,  55,  28,  41,   4,  38,  94,  77,  52,  14,
        11,  75], dtype=int32)

In [91]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 47, 75, 55, 28, 41, 25, 38, 75, 75, 52, 25, 25, 75],
      dtype=int32)

In [93]:
# 17. np.swapaxes

In [94]:
# 18. np.uniform

In [95]:
# 19. np.count_nonzero

In [96]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [97]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [98]:

# 25. np.allclose and equals