### What is numpy?
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences
NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### By default, arrays in numpy are floats

### Creating Numpy Arrays

In [ ]:
import numpy as np

# 1D array is a vector
a = np.array([1, 2, 3, 4, 5])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [ ]:
# 2D array and 3D array

# 2D array is a matrix

b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.shape)
print(b)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [ ]:
# 3D array is a tensor

c = np.array([[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]]])
c.shape

(2, 3, 2)

In [9]:
# dtype -> So that we can create an array of the data type we want

np.array([1, 2, 3], dtype=float)
np.array([1, 2, 3], dtype=bool)
np.array([1, 2, 3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [10]:
# np.arange

np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
# steps
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [15]:
# with reshape
np.arange(1, 13).reshape(3, 4)
np.arange(1, 13).reshape(2, 6)
np.arange(1, 13).reshape(6, 2)
np.arange(1, 13).reshape(4, 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
# np.ones and np.zeros
# very helpful in initializing the weights in deep learning (neural networks)
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### np.random.random always generates numbers between 0 and 1 (more precisely: in the interval [0.0, 1.0) — including 0 but excluding 1).

🔹 Why does it do that?

Because NumPy is generating samples from a Uniform Distribution:

👉 Specifically:
Uniform(0, 1)

That means:

Every number between 0 and 1 has an equal probability
No bias toward any sub-range

In [18]:
# np.random

np.random.random((3, 4))

array([[0.83709139, 0.19881   , 0.55486715, 0.56056568],
       [0.85673366, 0.77681155, 0.46073127, 0.84142031],
       [0.60994615, 0.79496215, 0.98462353, 0.02185777]])

In [22]:
# np.linspace
# linearly spaced
# all the points will be at equal distance from their respective successor and predecessor points.
# linearly separable points in a given space.
np.linspace(-10, 10, 10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [23]:
np.linspace(-10, 10, 10, dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [21]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

### Array attributes

In [57]:
a1 = np.arange(10, dtype=np.int32)  # vector    # default datatype is float 
a2 = np.arange(12, dtype=float).reshape(3, 4) # matrix
a3 = np.arange(8, dtype=np.int64).reshape(2, 2, 2)  # tensor

In [ ]:
# ndim -> it tells about the number of dimensions of the numpy array
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [35]:
# shape
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [37]:
# size -> total number of elements in the array
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [45]:
# itemsize
print(a1.itemsize)  # int32
print(a2.itemsize)  # float
print(a3.itemsize)  # int64

4
8
8


In [46]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


# Heterogeneous data using dtype=object

Please go through this link: Very important
https://chatgpt.com/share/69c24f8f-f400-8008-9a17-731992d593e3

In [47]:
arr = np.array([1, 'A', 3.5, None], dtype=object)
print(arr)
print(arr.dtype)

[1 'A' 3.5 None]
object


### Changing Datatypes

In [60]:
# I can change the datatype if I want
# this does not change the data type in place, it doesnt modify the original array, rather creates and
# return a new one.

print(a3.dtype)
a3 = a3.astype(np.int32)
print(a3.dtype)

int64
int32


### Array Operations

In [61]:
a1 = np.arange(12).reshape(3, 4)
a2 = np.arange(12, 24).reshape(3, 4)

### Scalar Operations -> because its happening between a numpy array and a scalar value.

In [ ]:
# arithmetic
a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [64]:
a1 + 2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [65]:
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [66]:
a1 / 2

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [ ]:
# relational 

# <, >, ==, !=, etc.

a2 > 5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [68]:
a2 > 25

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [70]:
a2 > 15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [71]:
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

### vector operations -> because its happening between 2 numpy arrays

In [ ]:
# arithmetic

a1 + a2     # since the shape is same, we can perform this operation.
# same with /, -, **, * 

### Array functions

In [85]:
a1 = np.random.random((3, 3))
a1 = np.round(a1 * 100)
a1

array([[58., 94., 34.],
       [97., 42., 46.],
       [33., 80., 95.]])

In [86]:
# max/ min/ sum/ prod

# from the whole array
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))

97.0
33.0
579.0
8712467131737600.0


In [89]:
# what if I want minimum from every row/ column
# 0 -> column
# 1 -> row

print(np.max(a1, axis=0))
print(np.max(a1, axis=1))

[97. 94. 95.]
[94. 97. 95.]


In [94]:
# mean/ median/ std/ var

print(np.mean(a1, axis=0))
print(np.mean(a1))
print(np.median(a1, axis=1))

print(np.std(a1, axis=1))
print(np.var(a1, axis=1))

[62.66666667 72.         58.33333333]
64.33333333333333
[58. 46. 80.]
[24.65765601 25.03774928 26.41127705]
[608.         626.88888889 697.55555556]


In [95]:
# trigonometric functions

np.sin(a1)

array([[ 0.99287265, -0.24525199,  0.52908269],
       [ 0.37960774, -0.91652155,  0.90178835],
       [ 0.99991186, -0.99388865,  0.68326171]])

In [97]:
# dot product -> column of 1st array(matrix) should be equal to row of 2nd array(matrix)

a2 = np.arange(12).reshape(3, 4)
a3 = np.arange(12, 24).reshape(4, 3)

np.dot(a2, a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [99]:
# log and exponents

np.log(a1)
np.exp(a1)

array([[1.54553894e+25, 6.66317622e+40, 5.83461743e+14],
       [1.33833472e+42, 1.73927494e+18, 9.49611942e+19],
       [2.14643580e+14, 5.54062238e+34, 1.81123908e+41]])

In [103]:
# round/ floor/ ceil

a = np.random.random((2, 3)) * 100
print(a)

print(np.round(a))
print(np.floor(a))
print(np.ceil(a))

[[26.159833    5.12479719 25.85454663]
 [82.06209819 24.46963765 46.47982363]]
[[26.  5. 26.]
 [82. 24. 46.]]
[[26.  5. 25.]
 [82. 24. 46.]]
[[27.  6. 26.]
 [83. 25. 47.]]


### Indexing and Slicing

In [105]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3, 4)
a3 = np.arange(8).reshape(2, 2, 2)

In [106]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
print(a1[0])
print(a1[-1])

0
9


In [109]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [110]:
a2[1, 2]

6

In [111]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [112]:
a3[1, 0, 1]

5

In [113]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [115]:
a1[2:5]

array([2, 3, 4])

In [116]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [117]:
a2[0, :]

array([0, 1, 2, 3])

In [118]:
a2[:, 2]

array([ 2,  6, 10])

In [119]:
a2[1:, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [121]:
a2[::2, ::3]

array([[ 0,  3],
       [ 8, 11]])

In [123]:
a2[::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [124]:
a2[1, ::3]

array([4, 7])

In [126]:
a2[:2, 1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [129]:
a3 = np.arange(27).reshape(3, 3, 3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [130]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [132]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [133]:
a3[0, 1]

array([3, 4, 5])

In [134]:
a3[1, :, 1]

array([10, 13, 16])

In [135]:
a3[2, 1:, 1:]

array([[22, 23],
       [25, 26]])

In [137]:
a3[::2, 0, ::2]

array([[ 0,  2],
       [18, 20]])

### Iterating

In [141]:
a1

for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [142]:
a2

for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [143]:
a3

for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [145]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [146]:
# reshape

#### Transpose

In [148]:
# Transpose
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [149]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [150]:
# Same result
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

#### Ravel

In [ ]:
# ravel -> it converts every array into 1D array.

a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [152]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [153]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [154]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

#### mostly used when data coming from multiple sources. and we have to combine them. since the data is same(schema is same), we can literally stack them over one another.

In [158]:
# horizontal stacking

a4 = np.arange(12).reshape(3, 4)
a5 = np.arange(12, 24).reshape(3, 4)
print(a4)
print(a5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [159]:
np.hstack((a4, a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [160]:
np.hstack((a4, a5, a4))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [161]:
# vertical stacking

np.vstack((a4, a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

just the opposite of stacking

In [165]:
# horizontal splitting

a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [167]:
np.hsplit(a4, 2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [168]:
np.hsplit(a4, 4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [170]:
# vertical splitting

a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [171]:
np.vsplit(a5, 3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

In [ ]:
# this will throw an error

np.vsplit(a5, 2)

ValueError: array split does not result in an equal division

In [ ]:
a = [1, 2, 3]
a

[1, 2, 3]